version: '3.4'
services:
  generate:
    image: threevl:rustynode
    build:
      dockerfile: Dockerfile
      context: .
    user: circleci
    volumes:
      - ./build:/home/circleci/project/zk-merkle-tree/build
      - ./contracts:/home/circleci/project/zk-merkle-tree/contracts
