# .graphclientrc.yml
sources:
  - name: union
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/3VLINC/union-dao
documents:
  - ./src/queries.graphql
plugins:
  - pollingLive:
      defaultInterval: 1000