name: test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: packages/contracts
        run: |
          cd packages/contracts
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: packages/contracts
        run: |
          forge test -vvv
        id: test
